spring:
  threads:
    virtual:
      enabled: true
  application:
    name: wb-data-backend
  datasource:
    url: jdbc:mysql://localhost:3306/wb_data?useSSL=false&serverTimezone=UTC
    username: root
    password: ${DB_PASSWORD:1111}
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mapper/**/*.xml

server:
  port: 8080

wbdata:
  plugins:
    dir: ${WB_DATA_PLUGIN_DIR:/Users/wenbin/Projects/wb-data/plugins}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
