CREATE TABLE IF NOT EXISTS `wb_query_export_task` (
    `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `task_uuid` CHAR(36) NOT NULL COMMENT '对外暴露的任务ID',
    `user_id` BIGINT NOT NULL COMMENT '发起导出的用户',
    `group_id` BIGINT NOT NULL COMMENT '导出所属项目组',
    `datasource_id` BIGINT NOT NULL COMMENT '数据源ID',
    `database_name` VARCHAR(128) NULL COMMENT '执行时所选数据库',
    `sql_text` LONGTEXT NOT NULL COMMENT '导出时提交的SQL快照',
    `format` VARCHAR(16) NOT NULL COMMENT 'csv | xlsx',
    `status` VARCHAR(32) NOT NULL COMMENT 'PENDING | RUNNING | SUCCESS | FAILED',
    `file_name` VARCHAR(255) NULL COMMENT '下载文件名',
    `file_path` VARCHAR(500) NULL COMMENT '文件存储路径',
    `row_limit` INT NOT NULL DEFAULT 100000 COMMENT '导出行数上限',
    `exported_rows` INT NULL COMMENT '实际导出行数',
    `truncated` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否截断',
    `error_message` VARCHAR(500) NULL COMMENT '失败原因',
    `expires_at` DATETIME NULL COMMENT '文件过期时间',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY `uk_wb_query_export_task_uuid` (`task_uuid`),
    KEY `idx_wb_query_export_task_user_group_created` (`user_id`, `group_id`, `created_at`),
    KEY `idx_wb_query_export_task_status` (`status`),
    CONSTRAINT `fk_wb_qet_user` FOREIGN KEY (`user_id`) REFERENCES `wb_user` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_wb_qet_group` FOREIGN KEY (`group_id`) REFERENCES `wb_project_group` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='查询导出任务';
