kestra:
  server:
    basic-auth:
      enabled: false
  repository:
    type: h2
  storage:
    type: local
    local:
      base-path: /app/storage
  queue:
    type: h2
  tasks:
    tmp-dir:
      path: /tmp/kestra-wd/tmp
  plugins:
    configurations:
      - type: io.kestra.plugin.scripts.runner.docker.Docker
        values:
          volumeEnabled: true
  tutorial-flows:
    enabled: false
